In [1]:
import tensorflow as tf
print('My first colab script!')

My first colab script!


First notebook in Google Colab


In [0]:
import tensorflow as tf

In [0]:
import numpy as np

In [0]:
x1 = np.zeros((4,4))

In [0]:
print(x1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
